export enum GradeLevelRankEnum {
  BEGINNERS_JOURNEY = "es",
  RISING_STAR = "ms",
  PROFICIENT_LEARNER = "hs",
  SKILLED_NAVIGATOR = "ksat",
  GLOBAL_COMMUNICATOR = "toeic",
  ACADEMIC_CHALLENGER = "toefl",
  MASTER_OF_PROFICIENCY = "teps",
  ELITE_THINKER = "sat",
  LANGUAGE_VIRTUOSO = "ielts",
  GRADUATE_EXPLORER = "gre",
  BUSINESS_STRATEGIST = "gmat",
  ULTIMATE_ACHIEVER = "act",
}
